### ISSUE TITLE
Suchseite (=Wireframe 2a): Spezialzeichen in Transkription werden nicht gesucht

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-es#37]
Nicht richtig indiziert in ES sind anscheinend:

- ```_```
- ```*``` ein *ꜥpš (dm4619) wird nicht gefunden
- ```⸮```
- ```?```

**Comment by dwerning** [comment]
**Problem**
Zwei einfach umzusetzende Szenarien:
1.  '*ꜥpš' findet '*ꜥpš' aber nicht 'ꜥpš'; 'ꜥpš' findet ''ꜥpš' aber nicht '*ꜥpš' ('`*`' wird nicht ignoriert)
2. 'ꜥpš' und '*ꜥpš' finden beide 'ꜥpš' und '*ꜥpš' ('`*`' wird ignoriert)

Ein Mischzenario
3. '*ꜥpš' findet '*ꜥpš' aber nicht 'ꜥpš'  ('`*`' wird lemmaseitig nicht ignoriert); 'ꜥpš' findet ''ꜥpš' und '*ꜥpš' ('`*`' wird lemmaseitig ignoriert)
ist schwer umzusetzen, perspektivisch aber sinnvoll.

**Angestrebt**
Verhalten 1 für `_`, `-`, `+`,   
Verhalten 2 für `⸮`, `{`, `}`, `⸢`, `⸣`, `〈`, `〉`.
Sonderbedeutung (RegEx) für: `§` (legacyTLA wildcard), `*` (common wildcard), `$` (word end), `[  ]` (set), `?` (optional, RegEx), `(  )` (optional, ägyptologisch).

**Comment by dwerning** [comment]
3.Aug.
** normal gefunden**
- `_` funktioniert
- `-` funktioniert
- `+` funktioniert
- `.` funktioniert
- ` ` funktioniert

**werden in Suchstring und Lemma ignoriert**
- `⸮, {, }, ⸢, ⸣, 〈, 〉` wird ignoriert

**werden in Lemma ignoriert**
- `*`

BTW:
- Maskierung `\*` *funktioniert nicht wie erwartet*, macht aber auch keinen Sinn => https://github.com/thesaurus-linguae-aegyptiae/tla-es-DEV/issues/9
- Maskierung `\.` *funktioniert nicht*, macht aber auch keinen Sinn, da defaultmäßig alle `.` als `\\.` gesucht werden
