### ISSUE TITLE
TLA-es als Service

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-es#80]
Zurzeit wird tla-es durch den User root ausgeführt. Wird der (physische) Server neugestartet bspw. am Wartungstag, dann erfolgt kein automatischer Neustart des tla-es und die Datenbank/Backend des TLA ist nicht erreichbar.
Aufgabe: ./gradlew run als service in systemd einrichten.

**Comment by dwerning** [comment]
Duplicate of 
- https://github.com/thesaurus-linguae-aegyptiae/tla-es/issues/81
